# Generated by Django 2.0.3 on 2018-05-17 10:48

from django.db import migrations, models
import django_jalali.db.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_book',
            name='BID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user_book',
            name='release_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='user_book',
            name='address',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
