# Generated by Django 2.0.3 on 2018-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180517_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book',
            name='BID',
            field=models.CharField(auto_created=True, max_length=5, unique=True),
        ),
    ]
