# Generated by Django 2.0.3 on 2018-05-20 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180520_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book',
            name='BID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
