# Generated by Django 2.0.3 on 2018-05-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180520_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book',
            name='BID',
            field=models.CharField(editable=False, max_length=5),
        ),
    ]
