# Generated by Django 2.0.3 on 2018-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180520_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_book',
            name='BID',
        ),
        migrations.AddField(
            model_name='book',
            name='BID',
            field=models.CharField(default='dfdsc', editable=False, max_length=5),
            preserve_default=False,
        ),
    ]
