# Generated by Django 2.0.3 on 2018-06-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180520_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.URLField(default=None),
        ),
    ]
