# Generated by Django 2.0.3 on 2018-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20180606_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='123', max_length=17),
            preserve_default=False,
        ),
    ]
