# Generated by Django 2.0.3 on 2018-06-13 17:34

from django.db import migrations, models
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180608_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon')),
                ('location_lat', osm_field.fields.LatitudeField(validators=[osm_field.validators.validate_latitude])),
                ('location_lon', osm_field.fields.LongitudeField(validators=[osm_field.validators.validate_longitude])),
            ],
        ),
        migrations.RemoveField(
            model_name='user_book',
            name='address',
        ),
        migrations.AlterField(
            model_name='tempbook',
            name='pic',
            field=models.URLField(blank=True),
        ),
    ]
