# Generated by Django 2.0.3 on 2018-06-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_user_book_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
