# Generated by Django 2.0.3 on 2018-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20180614_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.URLField(default='https://static-6.studiobebop.net/manga_hunters/volume_covers/1945054794.jpg', max_length=500),
        ),
    ]
